### ISSUE TITLE
Validate the `Dataplane` object

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#182]
* Making sure that the `tags` have the mandatory `service` field.
* Making sure that `inboud` is always present.
* Validate the values in each field, including making sure that the `interface` value matches the right format.
* Making sure the names are valid with no weird characters (ie, `[a-zA-Z0-9\-\_]+`).
* And so on.

But really, do this for **every object** not just `Dataplane`.

**Comment by jakubdyszkiewicz** [comment]
Done
