### ISSUE TITLE
Provide a sample service for demo purposes

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#187]
Provide a sample service for demo purposes that can echo back the requests we are making, it could be using something like https://echo.labstack.com/guide under the hood.

The executable will be called `echo-http-example`. Ideally, we could also build a gRPC variant of it (`echo-grpc-example`).

**Comment by jakubdyszkiewicz** [comment]
Done. We've got `tcp-echo` and we also have kuma-demo now.
