### ISSUE TITLE
HTTP API: Deleting unexisting resources should return 404

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#190]
Instead of `200 OK`: 

```sh
$ curl -i -X DELETE http://localhost:5681/meshes/asd
HTTP/1.1 200 OK
Date: Sun, 08 Sep 2019 19:28:16 GMT
Content-Length: 0
```

**Comment by yskopets** [comment]
Post actions:
* update `kumactl delete` respectively

**Comment by jakubdyszkiewicz** [comment]
> Post actions:
> 
> * update `kumactl delete` respectively

What do you mean? Should cmd return code 1 instead of 0 when resource does not exist?
