### ISSUE TITLE
./bin/kumactl install control-plane generates images that are not available in bintray.

### ISSUE THREAD

**Issue by kiyose** [Kong/kuma#235]
### Summary

Standard installation fails due to missing docker image.

### Steps To Reproduce

1. Download kuma-0.1.0-darwin.tar.gz
2. run ./bin/kumactl install control-plane  | kubectl apply -f -
3. kubectl -n kuma-system describe pods | grep Failed
Warning  Failed     11m (x4 over 12m)     kubelet, kind-control-plane  Failed to pull image "kong-docker-kuma-docker.bintray.io/kuma-injector:0.1.0-2-ga5a27f5": rpc error: code = Unknown desc = failed to resolve image "kong-docker-kuma-docker.bintray.io/kuma-injector:0.1.0-2-ga5a27f5": no available registry endpoint: kong-docker-kuma-docker.bintray.io/kuma-injector:0.1.0-2-ga5a27f5 not found

### Additional Details & Logs
This commit appears to be responsible for the error.
https://github.com/Kong/kuma/commit/d047661f7e5213f641332918ec190c75d8b4976d

- Version 0.1.0-2-ga5a27f5

- Error logs
$ docker pull kong-docker-kuma-docker.bintray.io/kuma-injector:0.1.0-2-ga5a27f5 
Error response from daemon: manifest for kong-docker-kuma-docker.bintray.io/kuma-injector:0.1.0-2-ga5a27f5 not found: manifest unknown: The named manifest is not known to the registry.

- Configuration
- Platform and Operating System
mac os running kubernetes in `kind`

**Comment by devadvocado** [comment]
I was able to replicate it, seems like an issue with the kuma-injector image. @gszr @dhruv  could you take a look at the bintray to see what's going on?

**Comment by gszr** [comment]
@devadvocado - We will cut a new release soon. @kiyose Thanks for the report.

**Comment by gszr** [comment]
@kiyose We have just released v0.1.1 including the fix for this issue! Once again, thanks for reporting!

**Comment by devadvocado** [comment]
![image](https://user-images.githubusercontent.com/49530888/64645887-bda3e480-d3ca-11e9-863f-1611eb659b06.png)
Looks good to me!

Let us know if you find anything else!

**Comment by subnetmarco** [comment]
Fixed in Kuma `0.1.1` available [here](https://kuma.io/install/0.1.1).

**Comment by kiyose** [comment]
Works for me. Thanks for the quick turnaround.
