### ISSUE TITLE
Introduced `describe` as a new CLI command for our entities

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#252]
For example:

```sh
$ kumactl describe dp-echo-1 --mesh default
type: Dataplane
mesh: default
name: backend-1
networking:
  inbound:
  - interface: 127.0.0.1:8000:80
    tags:
      service: backend
  outbound:
  - interface: :10000
    service: redis
```

**Comment by tharun208** [comment]
Hi, @subnetmarco  I like to work on this 😃

**Comment by jakubdyszkiewicz** [comment]
Hey,
I think it would be much better to implement get command for single resources like. `kumactl get dataplane dp-echo-1` 
Then we could provide -oyaml argument, so the result would be the same.

There is some work for this here https://github.com/Kong/kuma/pull/344

**Comment by subnetmarco** [comment]
I agree with @jakubdyszkiewicz, this command becomes:

```
$ kumactl get [entity_type] [entity_name]
```

For example

```
$ kumactl get mesh default
```

or:

```
$ kumactl get trafficroute example-route
```

or:

```
$ kumactl get trafficroute example-route --mesh production
```

## Blockers

In order to implement this functionality there is a missing feature that we need to implement:

* [Issue #661](https://github.com/Kong/kuma/issues/661)

## Output

### Found / Not Found

When found always return the specific entity (1 row per result) with exit code `0`. When not found return the following message with exit code `1`:

```
No resources found in default mesh.
```

or if the user specifies a specific mesh with `--mesh` like `hello-world` then it becomes:

```
No resources found in hello-world mesh.
```

### Default Format

The default format is always:

```
MESH	NAME		AGE
default	sample-route	3h5m
```

Example:

```
$ kumactl get mesh default
MESH	NAME	AGE
default	default	3h5m

$ kumactl get trafficpermission allow-all --mesh production
MESH		NAME		AGE
production	allow-all	3h5m
```

### Format

We can specify different formats with the `-o` argument like we do currently:

```
-o, --output string   output format: one of table|yaml|json (default "table")
```

For example:

```
$ kumactl get mesh default -oyaml
type: Mesh
name: demo
mtls:
  enabled: false
  ca:
    builtin: {}

$ kumactl get trafficroute example-route 
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  namespace: default
  name: route-1
spec:
  sources:
    - match:
        service: backend
  destinations:
    - match:
        service: redis
  conf:
    - weight: 90
      destination:
        service: redis
        version: '1.0'
    - weight: 10
      destination:
        service: redis
        version: '2.0'
```

**Comment by jakubdyszkiewicz** [comment]
@subnetmarco How is #661 a blocker for this? Can we add an 'AGE' column as an improvement?

```
$ kumactl get trafficroute example-route -oyaml
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  namespace: default
  name: route-1
spec:
  sources:
    - match:
        service: backend
  destinations:
    - match:
        service: redis
  conf:
    - weight: 90
      destination:
        service: redis
        version: '1.0'
    - weight: 10
      destination:
        service: redis
        version: '2.0'
```
This should be Kuma entity not K8S entity, right?
