### ISSUE TITLE
kuma sidecar injection not working

### ISSUE THREAD

**Issue by ptualek** [Kong/kuma#258]
### Summary

kuma sidecar injection not working

### Steps To Reproduce

1. Deploy k8s 1.14.6 with RBAC
2. Deploy kuma 0.1.2 with command 'kumactl install control-plane | kubectl apply -f -'
3. Deploy sample application with command 'kubectl apply -f https://raw.githubusercontent.com/Kong/kuma/master/examples/kubernetes/sample-service.yaml'
4. try to get meshes and dataplanes

### Additional Details & Logs
$ kumactl get meshes
NAME      mTLS   DP ACCESS LOGS
default   on     off

$ kumactl get dataplanes
MESH   NAME   TAGS

$ kubectl get pod -n kuma-app
NAME                            READY   STATUS    RESTARTS   AGE
kuma-tcp-echo-b968575b8-crlh9   1/1     Running   0          23m
kuma-tcp-echo-b968575b8-rcbm8   1/1     Running   0          23m

- Platform and Operating System
K8S: 1.14.6
Kernel: 3.10.0-957.27.2.el7.x86_64 (CentOS 7)
Docker: docker-ce 18.9.6
kumactl: 0.1.2

**Comment by yskopets** [comment]
@ptualek Hi!

I think, the issue is that `Control Plane` is not ready yet by the time you deploy the `sample app`.

Apparently, it takes time to download Docker images from `bintray.io` (where `kuma` is hosted for now).

As a result,  you run `kubectl apply -f <sample app>` much earlier than `kuma-injector` has been dowloaded and started by kubernetes.

In the long term, we should improve `kumactl` to handle that ordering for you.

But for now, could you please try to deploy once again using the following sequence of commands ?

```
# original command from Getting Started
kumactl install control-plane | kubectl apply -f -

# extra commands to wait until Kuma Control Plane is up-and-running
kubectl wait --timeout=120s --for=condition=Available -n kuma-system deployment/kuma-injector
kubectl wait --timeout=60s --for=condition=Ready -n kuma-system pods -l app=kuma-injector
kubectl wait --timeout=120s --for=condition=Available -n kuma-system deployment/kuma-control-plane
kubectl wait --timeout=60s --for=condition=Ready -n kuma-system pods -l app=kuma-control-plane

# original command from Getting Started
kubectl apply -f https://raw.githubusercontent.com/Kong/kuma/master/examples/kubernetes/sample-service.yaml
```

Please let me know if that helps.

**Comment by ptualek** [comment]
@yskopets Thanks for reply but I have tested it again with your suggestion but still not work.

`~$ kumactl install control-plane | kubectl apply -f -
namespace/kuma-system created
secret/kuma-injector-tls-cert created
secret/kuma-sds-tls-cert created
serviceaccount/kuma-control-plane created
customresourcedefinition.apiextensions.k8s.io/dataplaneinsights.kuma.io created
customresourcedefinition.apiextensions.k8s.io/dataplanes.kuma.io created
customresourcedefinition.apiextensions.k8s.io/meshes.kuma.io created
customresourcedefinition.apiextensions.k8s.io/proxytemplates.kuma.io created
customresourcedefinition.apiextensions.k8s.io/trafficpermissions.kuma.io created
clusterrole.rbac.authorization.k8s.io/kuma:control-plane created
clusterrolebinding.rbac.authorization.k8s.io/kuma:control-plane created
role.rbac.authorization.k8s.io/kuma:control-plane created
rolebinding.rbac.authorization.k8s.io/kuma:control-plane created
service/kuma-injector created
service/kuma-control-plane created
deployment.apps/kuma-injector created
deployment.apps/kuma-control-plane created
mutatingwebhookconfiguration.admissionregistration.k8s.io/kuma-injector-webhook-configuration created
~$ kubectl wait --timeout=120s --for=condition=Available -n kuma-system deployment/kuma-injector
deployment.extensions/kuma-injector condition met
~$ kubectl wait --timeout=60s --for=condition=Ready -n kuma-system pods -l app=kuma-injector
pod/kuma-injector-7cdd4c468d-9xzff condition met
~$ kubectl wait --timeout=120s --for=condition=Available -n kuma-system deployment/kuma-control-plane
deployment.extensions/kuma-control-plane condition met
~$ kubectl wait --timeout=60s --for=condition=Ready -n kuma-system pods -l app=kuma-control-plane
pod/kuma-control-plane-6cc677d9-v4mlq condition met
~$ kubectl apply -f https://raw.githubusercontent.com/Kong/kuma/master/examples/kubernetes/sample-service.yaml
namespace/kuma-app created
service/kuma-tcp-echo created
deployment.apps/kuma-tcp-echo created
~$ kubectl get pod -n kuma-app
NAME                            READY   STATUS              RESTARTS   AGE
kuma-tcp-echo-b968575b8-bf9m7   0/1     ContainerCreating   0          5s
kuma-tcp-echo-b968575b8-gblkf   0/1     ContainerCreating   0          5s`

**Comment by ptualek** [comment]
@yskopets I figured out something, but still need testing. I think it related to proxy because our k8s is behind a corporate proxy which I think I have to set no_proxy to .svc and .svc.cluster.local.

Let's me test it and I will report back.

**Comment by ptualek** [comment]
@yskopets I already tested kuma sidecar injection with add no_proxy *.svc and *.svc.cluster.local to API Server.

Now Kuma is able to inject sidecar into the POD.

I will close this issue now Thanks.

**Comment by devadvocado** [comment]
If you have any other questions after the sidecar injection step, feel free to join our slack at https://chat.kuma.io

**Comment by ptualek** [comment]
@devadvocado btw if you could add this into a document for those ppl who would have problem with corporate proxy, it would be good. Thanks
