### ISSUE TITLE
Universal  kuma-dp run error

### ISSUE THREAD

**Issue by gl81567405** [Kong/kuma#270]
kuma-tcp-echo is running.
centos 7 shell:

echo "type: Dataplane
mesh: default
name: dp-echo-1
networking:
  inbound:
  - interface: 127.0.0.1:10000:9000
    tags:
      service: echo" | kumactl apply -f -
KUMA_CONTROL_PLANE_BOOTSTRAP_SERVER_URL=http://127.0.0.1:5682 \
KUMA_DATAPLANE_MESH=default \
KUMA_DATAPLANE_NAME=dp-echo-1 \
kuma-dp run

Error: Invalid configuration: .ControlPlane is not valid: .BootstrapServer is not valid: .URL must be non-empty; .URL must be a valid absolute URI; .Dataplane is not valid: .Name must be non-empty

**Comment by jakubdyszkiewicz** [comment]
Hi @gl81567405 
can you try running kuma-dp with:
```
kuma-dp run --name=dp-echo-1 --mesh=default --cp-address=http://127.0.0.1:5682
```
and without env vars

**Comment by gl81567405** [comment]
@jakubdyszkiewicz  demo can run.thanks.

**Comment by jakubdyszkiewicz** [comment]
Thanks for reporting this. We'll fix the docs.
