### ISSUE TITLE
Extend SQL script generated by `kumactl install database-schema`

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#275]
### Summary

Extend SQL script generated by `kumactl install database-schema` to include the following:
* put resources table into a dedicated DB (e.g., `kuma`)
* put resources table into a dedicated Schema (e.g., `kuma`)
* create a dedicated user account to own DB/Schema (e.g., `kuma-admin`)
* create a dedicated user account to represent kuma-cp connecting to DB [should have very limited set of permissions comparing to the owner] (e.g., `kuma-cp`)

**Comment by nickolaev** [comment]
#617 obsoletes this one. Closing.
