### ISSUE TITLE
Add `kumactl delete` command

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#279]
### Summary

* Add `kumactl delete` command
  * only support removal of individual resources, namely
     ```
     DELETE /meshes/<mesh name>
     DELETE /meshes/<mesh name>/<policy type>/<policy name>
     ```
  * only support removal in `universal` mode (requires no extra development since Kuma API runs in read-only mode on `k8s`)

**Comment by pradeepmurugesan** [comment]
@yskopets I can work on this

**Comment by yskopets** [comment]
@pradeepmurugesan Hi!

Thanks a lot for you interest in `Kuma`! We will greatly appreciate your contribution.

I've updated description to clarify the scope of the task.

Feel free to ask any questions along the way (either here or on [Slack](https://kuma.io/community/)).

Goo luck!

**Comment by subnetmarco** [comment]
Hi @pradeepmurugesan! How's progress on this PR going? Let us know if you need any help from our side.

**Comment by pradeepmurugesan** [comment]
Hey @subnetmarco .. Thanks for checking. Working on the issue.. Will be a bit slow this week. Here is my work so far. Draft PR. https://github.com/Kong/kuma/pull/343

**Comment by yskopets** [comment]
@pradeepmurugesan Thanks a lot for your contribution!
