### ISSUE TITLE
Exclude `Namespace` from `Kuma Core` model

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#282]
### Summary

* at the moment, `Kuma Core` model includes `Namespace` field (to make mapping onto `k8s` objects straightforward)
* however, in `universal` mode there are no `Namespaces`
* furthermore, for consistency between `k8s` and `universal` we're ignoring `Namespace` in the core logic

**Comment by jakubdyszkiewicz** [comment]
Solved with #458
