### ISSUE TITLE
Support `kumactl get` for individual resources, e.g. `kumactl get <type> <name>`

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#283]
### Summary

* Support `kumactl get` for individual resources, e.g. `kumactl get <type> <name>`
* On `k8s` the behaviour should be the following:
  * `kumactl get <type>` should return a list of resources where `name` of each resource is formatted as `<k8s name>.<k8s namespace>`, e.g. `sample-policy.demo-namespace`
  * `kumactl get <type> <name>` should treat `<name>` as an opaque string and pass it to Kuma API server "as is", e.g. `kumactl get traffic-logs sample-log.demo-namespace`
  * inside control plane, formatting and parsing of `<k8s name>.<k8s namespace>` names should be incapsulated into `k8s`-specific implementation of `ResourceStore` abstraction
  * there will be no support for filtering by `<k8s namespace>`

**Comment by michal-franc** [comment]
Based on the list from `kumactl install control-plane` there are 5 custom resources:
- DataplaneInsight
- Dataplane
- Mesh
- ProxyTemplate
- TrafficLog
- TrafficPermission

We want `kumactl` to support all of them?

**Comment by yskopets** [comment]
Yes.

Don't worry if it won't work for `Mesh` on `k8s`. It's a special case.

**Comment by nickolaev** [comment]
This should be implemented. @jakubdyszkiewicz what do you think?

**Comment by tharun208** [comment]
@nickolaev, we already implemented this #667
