### ISSUE TITLE
`kuma-cp` should provide an endpoint to return locations of individual components, such as `bootstrap server`, `api server`, etc 

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#315]
### Summary

* `kuma-cp` should provide an endpoint to return locations of individual components, such as `bootstrap server`, `api server`, etc 

### Motivation

* enable #314
* allow evolution of Kuma endpoints without a need to modify existing deployments, e.g. migrate `bootstrap server` from `HTTP` to `HTTPS`  

### Example

```
{
  "apis": {
    "bootstrap": {
      "url": "http://kuma-control-plane:5682"
    },
    "initial-token": {
      "url": "https://kuma-control-plane:5683"
    }
  }
}
```

**Comment by jakubdyszkiewicz** [comment]
Does location includes port only or host + port?
If host + port, then what is the source of host, configuration of kuma-cp?
Can you list all components that should be present in the response?
Should this be another server or can we maybe merge diagnostic server with it?

**Comment by yskopets** [comment]
> Does location includes port only or host + port?

It should include a full URL, including protocol and port, e.g. `https://kuma-control-plane:5682`.
It will allow to migrate, eventually, from HTTP to HTTPS.

> If host + port, then what is the source of host, configuration of kuma-cp?

Yes. Configuration of `kuma-cp` should include DNS name it's reachable at. With that in place, `bootstrap server` URL should be inferred automatically.

> Can you list all components that should be present in the response?

At the moment, we only need `bootstrap server`. The next candidate is `initial token server`.

> Should this be another server or can we maybe merge diagnostic server with it?

It can be the same server that serves `/`
