### ISSUE TITLE
Please add a license file to this repo

### ISSUE THREAD

**Issue by mbrukman** [Kong/kuma#320]
Per the [`README`][readme]'s "License" section, Kuma is provided under the Apache 2.0 license. However, there isn't a `LICENSE` file at the top of the repo, so GitHub does not display the license on the [repo overview][github-blog-license-repo-overview].

Would it be possible to add a `LICENSE` file to the top of the repo with the verbatim contents of the [Apache 2.0 license][apache-2.0] to ensure the visibility of the license to make this clear?

Thanks!

[readme]: https://github.com/Kong/kuma/blob/bf4225863050e5e1e13ccce95f7b308e5af39ba3/README.md#license
[github-blog-license-repo-overview]: https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/
[apache-2.0]: https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by jakubdyszkiewicz** [comment]
Hi @mbrukman 
Good point, added a `LICENSE` file.
