### ISSUE TITLE
Infer bootstrapParam.xdsHost

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#323]
### Summary

Once #315 is done, we will have config property of public facing Kuma hostname. This name should be used for `BootstrapParamsConfig#XdsHost` by default instead of localhost.

Connected issue #322

**Comment by yskopets** [comment]
Just to clarify, in order to infer `BootstrapParamsConfig#XdsHost` we shouldn't make an HTTP request to the endpoint described in #315.

Instead, the value of a new configuration property that will be introduced as part of #315 should become the default value for  `BootstrapParamsConfig#XdsHost`.
