### ISSUE TITLE
`kumactl` commands with `-ojson` option should prettify output JSON 

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#357]
### Summary

* `kumactl` commands with `-ojson` option should prettify output JSON, i.e.
  * `kumactl get meshes -ojson`
  * `kumactl inspect dataplanes -ojson`

### Steps To Reproduce

1. Run
```
$ kumactl get meshes -ojson
```

The output will be:
```
{"items":[{"mtls":{"ca":{"builtin":{}},"enabled":true},"name":"default","type":"Mesh"}]}
```

### Expected behaviour

* output JSON should be prettified, i.e.
```
{
  "items": [
    {
      "mtls": {
        "ca": {
          "builtin": {}
        },
        "enabled": true
      },
      "name": "default",
      "type": "Mesh"
    }
  ]
}
```

**Comment by sterchelen** [comment]
@yskopets I can work on it !

**Comment by yskopets** [comment]
@sterchelen Hi!

Awesome! Please go ahead!
