### ISSUE TITLE
update k8s configuration generated by `kumactl install control-plane` to expose Kuma REST API in read-only mode

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#364]
### Summary

* update k8s configuration generated by `kumactl install control-plane` to expose Kuma REST API in read-only mode

### Expected outcome

1. Add `KUMA_API_SERVER_READ_ONLY=true` to the [Deployment](https://github.com/Kong/kuma/blob/8cf99cc/app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml#L87) of `kuma-control-plane`

**Comment by sterchelen** [comment]
@yskopets I can work on it :)

**Comment by yskopets** [comment]
@sterchelen Great! 

Thanks a lot for helping us!
