### ISSUE TITLE
add `--overwrite` option to `kumactl config control-planes add` command

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#380]
### Summary

* at the moment, `kumactl config control-planes add --name NAME --address ADDRESS` command fails if configuration already has a control plane registered under that name (which is useful to prevent human mistakes)
* however, as part of CI/CD the opposite behaviour - "add or replace" - would be useful as well
* as a solution, let's add `--overwrite` option to `kumactl config control-planes add` command
  * should be `false` by default
  * should be activated by simply adding `--overwrite` to the command line, e.g. `kumactl config control-planes add --name NAME --address ADDRESS --overwrite`

**Comment by Gabitchov** [comment]
Hi, I'll take this one too, if it is possible.

**Comment by yskopets** [comment]
@Gabitchov Hi!

Certainly! Thank you!  👍
