### ISSUE TITLE
build and publish `kumactl` Docker image as part of release

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#389]
### Summary

* at the moment, we already build `kumactl` Docker image as part of our CI pipeline (to run `e2e` tests on `Kubernetes` and `Docker Compose`)
* next, we will prepare a complete `Docker Compose`-based example for the end users, which requires a Docker image for `kumactl`

### Expected

* reuse existing `Dockerfile.kumactl` file (currently in `tools/ci/dockerfiles/`)
* move it to `tools/releases/dockerfiles`
* update release script to build and publish Docker image with `kumactl`
* update release build on CircleCI to make use of this published Docker image with `kumactl`

**Comment by tharun208** [comment]
I like to work on this

**Comment by yskopets** [comment]
@tharun208 Hi!

Awesome!

Thanks a lot for helping us!

**Comment by yskopets** [comment]
@tharun208 Hey!

Sorry, I had to fix it myself. It was blocking our release.
