### ISSUE TITLE
simplify `TrafficPermission`, `TrafficLog` and `TrafficRoute` resources by supporting only 1 rule per resource instead of a list of rules

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#394]
### Summary

* at the moment, `TrafficPermission`, `TrafficLog` and `TrafficRoute` resources allow to define a list of respective `rules` 
* although it saves a few lines of YAML, it also has negative impact on traceability (explaining to a user what is the origin of given Envoy configuration) 
* by reducing a list down to a single element, we are giving each `rule` a human-friendly reference name

**Comment by jakubdyszkiewicz** [comment]
Done
