### ISSUE TITLE
Can Kuma manage one global mesh across both VM and K8S?

### ISSUE THREAD

**Issue by chickenlj** [Kong/kuma#478]
Hi, I am new to Kuma, and I think the idea of Kuma of supporting both BrownField and GreenField applications is great. 

I got one question for you guys.

### Summary
I can understand install and deploy Kuma on Kubernetes, also I understand it can work on tradition VM clusters.  But is it possible for me to deploy one shared Kuma Mesh (one kuma-cp) that manages kuma-dp both in K8S and VM？
* kuma-cp can transparently coordinate service discovery across K8S and VM
* kuma-cp can send policies to K8S and VM accordingly with one universal operation and policy from kubectl

**Comment by RichiCoder1** [comment]
Ditto. The upsell seems to imply yes, but the docs make it seem no and it's quite confusing.

**Comment by nickolaev** [comment]
Duplication of #333. Closing.
