### ISSUE TITLE
Filter only gateway dataplanes via API or kumactl

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#505]
### Summary

Recently we introduced gateway dataplane to Kuma. This Dataplane does not define any `inbound`, but has `gateway` field in `networking`.

We want to be able to filter such dataplanes both using API and kumactl.

**Comment by tharun208** [comment]
Hi @jakubdyszkiewicz, I like to work on this

**Comment by tharun208** [comment]
@jakubdyszkiewicz , is that we need to have an API to filter out only the Dataplane without inbound and also how we will achieve this through kumactl?

**Comment by jakubdyszkiewicz** [comment]
I would start implementing it by adding the support for `dataplane_overview.go` endpoint and `kumactl inspect dataplanes` command, something like
`/{mesh}/dataplanes+insights?gateway=true` and on kumactl side `kumactl inspect dataplanes --gateway`

**Comment by tharun208** [comment]
okay, then that will be enough for filtering right ? or further development needs to be done after you added the support for `dataplane_overview.go`.

**Comment by jakubdyszkiewicz** [comment]
Yes, first add it to `dataplane_overview.go` and then add it in `kumactl`.

**Comment by devadvocado** [comment]
hey @tharun208, wanted to check in if you need any help on this. Thanks again for volunteering to tackle this!

**Comment by tharun208** [comment]
No @devadvocado , I am almost there, will push in a while

**Comment by tharun208** [comment]
Hi @devadvocado, Can I pair with someone to clear my doubts?

**Comment by tharun208** [comment]
I have few doubts, regarding this issue which are more into technical doubts.
1. We can add a query params to existing inspectDataplanes endpoint and based on the query param for gateway we need to show the results.
2. Do we also need to return the insights associated with the data planes?
3. Also, we need to pass the query param gateway to the `resManager.List(ctx, &dataplanes,
{ store.ListByName(mesh), gateway}` right ?.

**Comment by jakubdyszkiewicz** [comment]
1. that is correct
2. yes - with dataplane_overview_ws.go we should return insights
3. we cannot modify the ResourceManager interface just by adding a parameter
you can go two ways
a) just filter on `dataplane_overview_ws.go` the same way as with tags.
a) harder way - introduce a generic mechanism for extra filtering parameters. You would have to extend `ListOptions` with a way to add extra parameters that can be later used by custom resource manager for given resource (the same way as with mesh resource manager). If you want to go this way, please provide design before implementing this.

I think it's fine to go with a)

**Comment by tharun208** [comment]
Then coming to point 3) I just need to call `overviews.RetainMatchingTags(tags)` with my gateway query param right?. Correct me If I am wrong
