### ISSUE TITLE
load balancing for GRPC services 

### ISSUE THREAD

**Issue by gokhandincer** [Kong/kuma#548]
Hi everyone,

We use grpc services. As you know standart k8s service is not support grpc. We did install kuma. And we saw the traffic routed only one pod like standart service. Is there a way how to fix. I've read kuma documentation but i couldn't see anything about grpc.

Thanks.

**Comment by yskopets** [comment]
@gokhandincer Hi!

So far (`Kuma 0.3.x`), we've been mostly focused on `L4` (`TCP`) traffic to enable seamless introduction of Service Mesh into your infrastructure.

We will be introducing `L7` features (such as HTTP, gRPC, tracing) as part of `Kuma 0.4.x`.

It will be a series of `0.4.x` releases. One release every 3-4 weeks with a batch of new features. Starting in February. 

Hope that helps!

**Comment by gokhandincer** [comment]
Thank you @yskopets

**Comment by gokhandincer** [comment]
Hi @yskopets ,
You told that 0.4.x will support to gRPC before. Does 0.4.0 version support to gRPC. I couldn't see about gRPC implementation on README

Thanks.
