### ISSUE TITLE
support a use case where `kuma-cp` is running behind a gateway of some kind 

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#597]
### Summary

This issue was reported by @sudeeptoroy on [Kuma Slack](https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1582470516008900):

* `kuma-cp` exposes a `Catalog` endpoint with a list of URLs to all internal REST APIs (e.g., bootstrap API, admin API, monitoring assignment API, etc)
* at the moment, the contents of `Catalog` is automatically generated on `kuma-cp` start up and cannot be edited by users
* apparently, it causes a problem when a user wants to put `kuma-cp` behind a gateway of some kind (e.g., behind `k8s Ingress`)
* in that case `Catalog` endpoint returns URLs that are not pointing to gateway as a user would expect (consider gateway that changes protocol, fqdn and port)

# Expected behaviour

* there should be an easy way to run `kuma-cp` behind a gateway of some kind
* allowing users to override URLs in the `Catalog` might be a solution, but we should also consider other options

**Comment by sudeeptoroy** [comment]
reported by @sudeeptoroy ;)

**Comment by yskopets** [comment]
@sudeeptoroy corrected. sorry 😃

**Comment by sudeeptoroy** [comment]
This issue can be closed now.
