### ISSUE TITLE
Introduce a `%KUMA_MESH%` command operator into access log format

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#599]
### Summary

* Introduce a `%KUMA_MESH%` command operator into access log format

### Expected outcome

* Enable users to have mesh name in the access log

```
%KUMA_MESH% %KUMA_SOURCE_SERVICE% %KUMA_DESTINATION_SERVICE% ...
```

**Comment by pradeepmurugesan** [comment]
@yskopets I can pick this one 👍
