### ISSUE TITLE
kuma-cp migrate help text

### ISSUE THREAD

**Issue by doctorwu** [Kong/kuma#632]
### Summary
There is a discrepancy in the kuma-cp migrate command help text. The help text says the following:

>Migrate database to which Control Plane is connected. The database contains all policies, dataplanes and secrets. The schema has to be in sync with version of Kuma CP to properly work. Make sure to run "kumactl migrate up" before running new version of Kuma.

kumactl does not have a migrate command.

I believe it should read "kuma-cp  migrate up"

### Steps To Reproduce

1. Run  `kuma-cp migrate -h`
2.
3.
4.

### Additional Details & Logs

- Version: 0.4.0
- Error logs
- Configuration
- Platform and Operating System: All

**Comment by jakubdyszkiewicz** [comment]
Good catch, it should definitely be `kuma-cp migrate up`

**Comment by subnetmarco** [comment]
@doctorwu want to send a quick PR?
