### ISSUE TITLE
Support `-m` in addition to `--mesh` in kumactl

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#662]
Support `-m` in addition to `--mesh` in commands executed via `kumactl`, for example the following commands should be equivalent:

```sh
$ kumactl inspect dataplanes --mesh hello
...
$ kumactl inspect dataplanes -m hello
...
```

Make sure this works on `kumactl get` as well.

**Comment by tharun208** [comment]
since in `kumactl get` we agreed to have a generic get command which takes both the `type` and `name`. I think there is no need of adding this for `kumactl get`

**Comment by tharun208** [comment]
Raised a PR :) @subnetmarco

**Comment by subnetmarco** [comment]
> since in kumactl get we agreed to have a generic get command which takes both the type and name. I think there is no need of adding this for kumactl get

Since Kuma supports multiple meshes, each one with their own resources, it’s still valuable to be able to select what mesh we want to use.

**Comment by tharun208** [comment]
This should come for only dataplanes or all existing resources?

**Comment by tharun208** [comment]
and since our root command of kumactl accepts a mesh name, I think there is no need of making changes to get command. Correct me if I am wrong on this?

**Comment by jakubdyszkiewicz** [comment]
`--mesh` is global arg that works for all commands
