### ISSUE TITLE
Support Kuma on Kubernetes v1.18.0

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#676]
### Summary

Kubernetes v.1.18.0 introduces following change https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

Which makes Kuma incompatible with Kubernetes v1.18.0
```shell
$ echo "apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabled: true
    ca:
      builtin: {}" | kubectl apply -f -
The Mesh "default" is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`
```

As a part of this task, we should also add v1.18.0 to CI.

**Comment by nickolaev** [comment]
#720 introduces K8s 1.18.2 support. Closing.
