### ISSUE TITLE
Support tracing in order to visualise latency introduced by Kuma 

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#7]

**Comment by jcchavezs** [comment]
need help on this?

**Comment by subnetmarco** [comment]
@jcchavezs thanks for helping. We actually have introduced a Tracing Policy at https://kuma.io/docs/latest/policies/traffic-trace/ a while back, so I am going to close this issue.

But if you are looking to contribute more tracing features we would be happy to chat about this at our next community call. You can ping me on [Slack](https://kuma.io/community/) if you want to add this item to the agenda (I am `Marco`).
