### ISSUE TITLE
Homebrew support to install Kumactl

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#703]
As per title.

**Comment by tharun208** [comment]
This looks interesting ! I will work on it @subnetmarco @jakubdyszkiewicz

**Comment by subnetmarco** [comment]
Great, keep us updated @tharun208

**Comment by tharun208** [comment]
> Great, keep us updated @tharun208

@subnetmarco @jakubdyszkiewicz I am not finding separate tar files for `kumactl` in bintray. Only it is found in kuma-docker. Can we have a separate tar file for `kumactl` or can I build the `kumactl homebrew formula` from the Kuma tar by building only `kumactl` after extracting?

**Comment by nickolaev** [comment]
You can check how `istioctl` is built here:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb

They essentially compile only the `istioctl` and then install the generated binary.

**Comment by tharun208** [comment]
@nickolaev thanks much

**Comment by tharun208** [comment]
@subnetmarco @nickolaev @jakubdyszkiewicz 
I created the formula for `kumactl` with the current release cut `0.5.0-rc2`. Is this fine?

formula - https://github.com/tharun208/homebrew-core/blob/kumactl-0.5.0-rc2/Formula/kumactl.rb

**Comment by tharun208** [comment]
Merged to homebrew-core @subnetmarco 😃 
PR - https://github.com/Homebrew/homebrew-core/pull/53999

**Comment by nickolaev** [comment]
Good job @tharun208! Would you consider applying my suggestion in #708 for the homebrew? So you can use the tar and yet have the proper version set.

**Comment by nickolaev** [comment]
#728 adds support for `kumactl` completion generation. Can we please make these installed in Homebrew, similar to other popular tools?

**Comment by tharun208** [comment]
@nickolaev, we can add this support with our `0.5.0` release

**Comment by tharun208** [comment]
@nickolaev, The code completion is not a part of make file ?.

**Comment by nickolaev** [comment]
Kumactl is now officially in the brew repo:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/kumactl.rb

Closing this one.
