### ISSUE TITLE
Check if the kumactl version is the same as CP

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#725]
### Summary

To avoid situation that a user by accident use old version of `kumactl` with newer Kuma CP we can check if versions of kumactl and CP are the same.

To do this, at the start of kumactl we can do the request to API Server on path `/` that return
```
{
  "tagline": "Kuma"
  "version": "0.4.0"
}
```
and see if the version is the same as in kumactl. If it is not, we can print a warning
```
Warning: Your kumactl version is 0.3.2 which is not the same as 0.4.0 for CP. Update your kumactl.
```
and execute commands regardless if it's in sync or not.

@subnetmarco thoughts?

**Comment by tharun208** [comment]
@jakubdyszkiewicz, I ll work on this
