### ISSUE TITLE
Parse durations with `y`, `h`, `m` suffixes properly.

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#743]
ie, when setting up a certificate rotation of `24h` or a CA expiration of `10y`.

Right now we only support `h`.

**Comment by tharun208** [comment]
what if the `expiration` field is given like `2h30m`. Is this format allowed ?.Or we need to some round like we did for `age` column. @subnetmarco @jakubdyszkiewicz

**Comment by subnetmarco** [comment]
I wouldn't mind supporting the `2h30m` format too. @jakubdyszkiewicz ?

**Comment by jakubdyszkiewicz** [comment]
I'm ok with this as long as we are using lib (preferably standard lib) to do this and we are not parsing this by hand.

**Comment by subnetmarco** [comment]
Do we support both “4d” and “4d2h5m” formats?

**Comment by tharun208** [comment]
yes @subnetmarco it will support

**Comment by subnetmarco** [comment]
Re-opening because this is currently not working. @tharun208
