### ISSUE TITLE
Global/Local config infrastructure

### ISSUE THREAD

**Issue by nickolaev** [Kong/kuma#766]
### Summary

To support the Multi-cluster and Hybrid deployments as described in [multicluster.md](https://github.com/Kong/kuma/blob/master/docs/proposals/multicluster.md), the Kuma CP binary will be split functionally into a Global CP and Local CP. This issue is to provide the infrastructure, command-line flags, and the appropriate `kumactl install` mechanisms. No real functionality is envisioned here, rather this will enable project-wide configuration so that the following implementation can leverage the flash to enable/disable particular functionalities in the code.

This is a break down of the work we envision:

* have command line arguments to `kuma-cp run`. We want three modes `--standalone` (which is the default if not specified) `--local` and `--global`.
* whatever is configured on the command line should be available in the global kuma-cp config as a flag: https://github.com/Kong/kuma/blob/master/pkg/config/app/kuma-cp/config.go#L88
* We need a set of these to verify this works robustly

* We shoudl be able to call `kumactl install control-plane --local` and it should generate a `yaml` that invokes the `kuma-cp run --local`. Essentially it is templetasing this `yaml` at this place: https://github.com/Kong/kuma/blob/master/app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml#L90 and adding something like:
```yaml
    command: ["kuma-cp"]
    args: {{ .KumaCPArgs }}
```
The Generate `.KumaCPArgs` dynamically based on the provided flags.

**Comment by nickolaev** [comment]
@tharun208 please let me know if you need more information.

**Comment by tharun208** [comment]
looks fine @nickolaev

**Comment by tharun208** [comment]
@nickolaev we also need to have a validation if the user tries to run `kuma cp run` with this own config file?

**Comment by nickolaev** [comment]
Yes, and I assume the command line should take preference as it is explicit.
I was also thinking would `--mode [standalone|local|global]` make more sense than `--standalone`, `--local`, `--global`?

**Comment by tharun208** [comment]
> Yes, and I assume the command line should take preference as it is explicit.
> I was also thinking would `--mode [standalone|local|global]` make more sense than `--standalone`, `--local`, `--global`?

yes, `--mode` more sense
