### ISSUE TITLE
Mark Dataplanes/Ingress with cluster tag in Local

### ISSUE THREAD

**Issue by nickolaev** [Kong/kuma#802]
### Summary

When Dataplane is created in Local CP mode. CP should add automatically `cluster` tag for every inbound with cluster name defined in Local CP settings.

Edge cases:
* User adds this by hand - we should replace it.

K8s - pod converter
Universal - datplane manager, create inspired by mesh manager

kumactl install control-plane --mode local --cluster-name "name"

**Comment by tharun208** [comment]
I like to work on this
