### ISSUE TITLE
Kuma not properly load balancing when Kong is used as an ingress gateway

### ISSUE THREAD

**Issue by berinle** [Kong/kuma#822]
### Summary
Kuma not properly load balancing when Kong is used as an ingress gateway.

### Steps To Reproduce

1. Deploy kuma+kong into a k8s cluster (e.g. with https://bit.ly/demokumakong)
2. Deploy the sample echo service and scale it to 3 replicas (https://bit.ly/echo-service)
3. Query the upstreams via the Kong Admin API

**Expected result:**
There should be 3 targets for the upstream, matching the 3 instances of the service running.

**Actual result:**
There is only 1, thus traffic is only routed to 1 pod instead of being spread across the 3 pods.

### Additional Details & Logs
```
GET https://KONG_ADMIN_API:8444/upstreams/echo.kuma-demo.8080.svc/targets
{
  "next": null,
  "data": [
    {
      "created_at": 1591743770.159,
      "upstream": {
        "id": "1bc60c39-962c-5ad0-bcaf-5c06cdd38faa"
      },
      "id": "6ee4debb-0613-56bf-b6dd-7b4448bfb3ee",
      "target": "echo.kuma-demo.svc:8080",
      "weight": 100
    }
  ]
}
```

Verified there are `3` pods matching the label/selector
```
$ kubectl get po -A -l app=echo
NAMESPACE   NAME                   READY   STATUS    RESTARTS   AGE
kuma-demo   echo-78b867555-gsd98   2/2     Running   0          22h
kuma-demo   echo-78b867555-sc842   2/2     Running   0          44h
kuma-demo   echo-78b867555-zhhpk   2/2     Running   0          22h
```

Also verified with the Kuma UI
![2020-06-11_08-51-17](https://user-images.githubusercontent.com/82424/84387850-a3996b80-abc1-11ea-815f-8d0799d4ed95.png)

- Version: 0.5.0
- Platform and Operating System: Linux

**Comment by subnetmarco** [comment]
@berinle I believe that we answered to this problem on the Slack chat, correct?

**Comment by berinle** [comment]
Yes @subnetmarco, this was answered in slack but not fully addressed.

**Comment by berinle** [comment]
Closing this. Issue resolved. Started again from scratch and everything works as expected.
